# Generated by Django 4.1.7 on 2025-05-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('has_parent', models.BooleanField(default=True, verbose_name='Есть контактное лицо')),
                ('parent_first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя родителя')),
                ('parent_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия родителя')),
                ('parent_birthday', models.DateField(blank=True, null=True, verbose_name='День рождения родителя')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон родителя')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_is_required', models.BooleanField(default=True, verbose_name='Нужно ли напоминать?')),
                ('reminder_message', models.TextField(default='Добрый день.\r\nНапоминаем об уроке завтра dd.mm в hh:MM', verbose_name='Текст для напоминания')),
                ('report_is_required', models.BooleanField(default=True, verbose_name='Нужно ли сообщать о проведении?')),
                ('report_message', models.TextField(default='Добрый день.\r\nУрок провели.\r\nОсталось i оплаченных занятий из n', verbose_name='Текст для отчета')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='stuff.student')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(0, 'ПН'), (1, 'ВТ'), (2, 'СР'), (3, 'ЧТ'), (4, 'ПТ'), (5, 'СБ'), (6, 'ВС')], verbose_name='День недели')),
                ('timestamp', models.TimeField(verbose_name='Время')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='stuff.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='stuff.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
