# Generated by Django 4.2.20 on 2025-10-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='stuff.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='stuff.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reminder_message',
            field=models.TextField(default='Добрый день.\r\nНапоминаем об уроке завтра date в time', verbose_name='Текст для напоминания'),
        ),
    ]
