# Generated by Django 4.2.20 on 2025-10-28 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_alter_lesson_student_alter_lesson_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_lessons', to='stuff.lesson', verbose_name='Отмененное занятие')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('cancelled_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_lessons', to='stuff.cancelledlesson', verbose_name='Отмененное занятие')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_lessons', to='stuff.student', verbose_name='Ученик')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_lessons', to='stuff.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
